spring.application.name=speakly-backend

spring.ai.openai.api-key=${GROQ_API_KEY}
#spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.base-url=https://api.groq.com/openai/v1
#spring.ai.openai.chat.options.model=llama-3.3-70b-versatile
#spring.ai.openai.chat.options.max-tokens=1000
#spring.ai.openai.chat.options.temperature=0.2


spring.ai.openai.audio.transcription.options.model=whisper-large-v3
