spring.application.name=speakly-backend

spring.ai.openai.api-key=${GROQ_API_KEY}
#spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.base-url=https://api.groq.com/openai/v1
#spring.ai.openai.chat.options.model=llama-3.3-70b-versatile
#spring.ai.openai.chat.options.max-tokens=1000
#spring.ai.openai.chat.options.temperature=0.2
springdoc.swagger-ui.server-urls[0]=https://speakly-backend.duckdns.org
server.forward-headers-strategy=framework
server.tomcat.remoteip.internal-proxies=.*
server.tomcat.use-relative-redirects=true
# Fuerza a Swagger UI a usar una URL relativa para todas las peticiones
springdoc.swagger-ui.use-root-path=true

# Deshabilita la URL por defecto autogenerada
springdoc.swagger-ui.disable-swagger-default-url=true

# Sobreescribe directamente la lista de servidores en la UI de Swagger
springdoc.swagger-ui.server-urls=/


spring.ai.openai.audio.transcription.options.model=whisper-large-v3
